filter:
  excluded_paths:
    - tests/*
    - vendor/*
    - bin/*

checks:
  php:
    code_rating: true
    duplication: true
    custom_coding_standard:
      git_repository: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
      ruleset_path: phpcs.xml

tools:
    external_code_coverage: true
